apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c  
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always